application: seshat
version: 1
runtime: python
api_version: 1

handlers:
- url: .*/css
  static_dir: Web/templates/css
- url: .*/javascript
  static_dir: Web/templates/javascript
- url: .*/images
  static_dir: Web/templates/images
  
- url: .*
  script: main.py