application: chps-corpora
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: .*/css
  static_dir: Web/templates/css
- url: .*/javascript
  static_dir: Web/templates/javascript
- url: .*/images
  static_dir: Web/templates/images
  
- url: .*
  script: main.py